# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: noxos-app-management
before:
  hooks:
    - go generate
    - go run github.com/google/go-licenses@latest check . --disallowed_types=restricted
    - go mod tidy
    - sh -c "PKGS=$(go list ./... | grep -v '/pkg/docker$' | grep -v '/pkg/utils/downloadHelper$'); go test -race -v ${PKGS} -timeout 30m"
builds:
  - id: noxos-app-management-amd64
    binary: build/sysroot/usr/bin/noxos-app-management
    env:
      - CC=x86_64-linux-gnu-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - cmd: go build -v -tags 'musl netgo osusergo' -o build/sysroot/usr/bin/appfile2compose github.com/Nox-OS/NoxOS-AppManagement/cmd/appfile2compose
          output: true
  - id: noxos-app-management-arm64
    binary: build/sysroot/usr/bin/noxos-app-management
    env:
      - CC=aarch64-linux-gnu-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm64
    hooks:
      post:
        - cmd: go build -v -tags 'musl netgo osusergo' -o build/sysroot/usr/bin/appfile2compose github.com/Nox-OS/NoxOS-AppManagement/cmd/appfile2compose
          output: true
  - id: noxos-app-management-arm-7
    binary: build/sysroot/usr/bin/noxos-app-management
    env:
      - CC=arm-linux-gnueabihf-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
    hooks:
      post:
        - cmd: go build -v -tags 'musl netgo osusergo' -o build/sysroot/usr/bin/appfile2compose github.com/Nox-OS/NoxOS-AppManagement/cmd/appfile2compose
          output: true
  - id: noxos-app-management-riscv64
    binary: build/sysroot/usr/bin/noxos-app-management
    env:
      - CC=riscv64-linux-gnu-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - riscv64
    hooks:
      post:
        - cmd: go build -v -tags 'musl netgo osusergo' -o build/sysroot/usr/bin/appfile2compose github.com/Nox-OS/NoxOS-AppManagement/cmd/appfile2compose
          output: true
  - id: noxos-app-management-migration-tool-amd64
    binary: build/sysroot/usr/bin/noxos-app-management-migration-tool
    main: ./cmd/migration-tool
    env:
      - CC=x86_64-linux-gnu-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - amd64
  - id: noxos-app-management-migration-tool-arm64
    binary: build/sysroot/usr/bin/noxos-app-management-migration-tool
    main: ./cmd/migration-tool
    env:
      - CC=aarch64-linux-gnu-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm64
  - id: noxos-app-management-migration-tool-arm-7
    binary: build/sysroot/usr/bin/noxos-app-management-migration-tool
    main: ./cmd/migration-tool
    env:
      - CC=arm-linux-gnueabihf-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
  - id: noxos-app-management-migration-tool-riscv64
    binary: build/sysroot/usr/bin/noxos-app-management-migration-tool
    main: ./cmd/migration-tool
    env:
      - CC=riscv64-linux-gnu-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - riscv64
archives:
  - name_template: >-
      {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-v{{ .Version }}
    id: noxos-app-management
    builds:
      - noxos-app-management-amd64
      - noxos-app-management-arm64
      - noxos-app-management-arm-7
      - noxos-app-management-riscv64
    files:
      - build/**/*
  - name_template: >-
      {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-migration-tool-v{{ .Version }}
    id: noxos-app-management-migration-tool
    builds:
      - noxos-app-management-migration-tool-amd64
      - noxos-app-management-migration-tool-arm64
      - noxos-app-management-migration-tool-arm-7
      - noxos-app-management-migration-tool-riscv64
    files:
      - build/sysroot/etc/**/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: Nox-OS
    name: NoxOS-AppManagement
  draft: true
  prerelease: auto
  mode: replace
  name_template: "v{{ .Version }}"
