name: publish npm

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Set package version from tag
        run: |
          sudo apt-get update
          sudo apt-get --no-install-recommends --yes install jq
          VERSION="${GITHUB_REF#refs/tags/v}"
          jq '.version="'"${VERSION}"'"' package.json > package.json.new
          mv package.json.new package.json

      - name: Install build tooling
        run: |
          npm install -g yarn @openapitools/openapi-generator-cli

      - name: Build SDK
        run: |
          npm install
          npm run start

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token || secrets.NPM_TOKEN_PRIVATE }}
